#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 25 15:36:40 2017

@author: hsadeghi
"""

import scipy.signal as ss 
import matplotlib.pyplot as plt

plt.figure(1)
plt.subplot(2, 1, 1)
plt.plot(data_s)
plt.subplot(2, 1, 2)
f, t, sxx = ss.spectrogram(data_s, fs)
sxx = np.log(sxx)
plt.pcolor(t, f, sxx)